### ISSUE TITLE
Specify the desired operation with inputs

### ISSUE THREAD

**Issue by mscwilson** [mscwilson/changelog-creator#51]
Action inputs so it would be used like 

```yaml
      - name: Run ruby script
        id: release-notes
        uses: mscwilson/changelog-creator@0.1.0
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          operation: "github release notes"
```
